// svelte/src/App.svelte
<script>
	import Calendar from './lib/Calendar.svelte';
	import Clocks from './lib/Clocks.svelte';
	import Hero from './lib/Hero.svelte';
	import Layout from './lib/layouts/Layout.svelte';
	import Summary from './lib/Summary.svelte';
</script>

<Layout>
	{#snippet headache({ data, birthDate, name, percentage, lifeExpectancy })}
		<Hero {name} {percentage} {data} />
		<Clocks {data} />
		<Calendar {data} {lifeExpectancy} />
		<Summary {birthDate} {lifeExpectancy} />
	{/snippet}
</Layout>

// reactjs/src/App.jsx
import Calendar from "./components/Calendar"
import Clocks from "./components/Clocks"
import Hero from "./components/Hero"
import Layout from "./components/layouts/Layout"
import Summary from "./components/Summary"
import { calculateTimeLeft, getLifePercentageLived } from "./utils"


function App() {

  const birthDate = '1993-12-27'
  const lifeExpentancy = 80
  const data = calculateTimeLeft(birthDate, lifeExpentancy)
  console.log(data)
  const name = 'Kuot'

  const percentage = getLifePercentageLived(birthDate, lifeExpentancy)

  return (
    <Layout>
      <Hero name={name} data={data} percentage={percentage} />
      <Clocks data={data} />
      <Calendar />
      <Summary />
    </Layout>
  )
}

export default App
