// svelte/src/lib/Clocks.svelte
<script>
	import { getTimePercentage } from '../utils';

	let { data } = $props();
	let snapshot = getTimePercentage();
	console.log(data, snapshot);
</script>

<section id="clocks">
	<p><i>Time remaining in different units.</i></p>
	<div class="clocks-grid">
		{#each Object.keys(data) as clock, clockIndex}
			<div class="card clock-card">
				<div class="circle" style:rotate="{snapshot[clock]}deg" >
					<div class="ticker {clock}"></div>
				</div>
				<div>
					<h5>{data[clock]}</h5>
					<p>{clock}</p>
				</div>
			</div>
		{/each}
	</div>
</section>

// reactjs/src/components/Clocks.jsx
import { getTimePercentage } from '../utils';

function Clock(props) {
	const { percent, title, data } = props;

	return (
		<div className='card clock-card'>
			<div
				className='circle'
				style={{ transform: `rotate(${Math.round(percent)}deg)` }}
			>
				<div className={'ticker ' + title}></div>
			</div>
			<div>
				<h5>{data}</h5>
				<p>{title}</p>
			</div>
		</div>
	);
}

export default function Clocks(props) {
	const { data } = props;
	const snapshot = getTimePercentage();
    console.log(snapshot)
	return (
		<section id='clocks'>
			<p>
				<i>Time remaining in different units</i>
			</p>
			<div className='clocks-grid'>
				{Object.keys(data).map((clock, clockIndex) => {
					return (
						<Clock
							data={data[clock]}
							title={clock}
							percent={snapshot[clock]}
							key={clockIndex}
						/>
					);
				})}
			</div>
		</section>
	);
}
