// vue/src/components/Hero.vue
<script setup>
const { name, data, handleToggleModal, percentage, resetData } = defineProps({
	name: String,
	data: Object,
	handleToggleModal: Function,
	percentage: String,
    resetData: Function
});
console.log(name);

function copyLink() {
    navigator.clipboard.writeText("https://deathandtaxes.netlify.app")
    alert("Copied ☺️")
}
</script>

<template>
	<section id="hero">
		<h3 class="text-large">
			{{ name }}, you have {{ data['weeks'] }} weeks left. Make them count 🫡
		</h3>
		<div class="btns-container">
			<button @click="handleToggleModal">Not {{ name }}?</button>
			<button @click="copyLink" class="link-button">Copy Link</button>
			<button @click="resetData" class="link-button">Reset Data</button>
		</div>
		<div class="progress-bar">
			<div :style="{ width: percentage }">
				<div>
					<i class="fa-solid fa-baby"></i>
					<h6 class="bar-label">Birth</h6>
				</div>
				<h6>{{ percentage }}</h6>
			</div>
			<div>
				<h6 class="bar-label">Death</h6>
				<i class="fa-solid fa-skull"></i>
			</div>
		</div>
	</section>
</template>

<style scoped></style>

// svelte/src/lib/Hero.svelte
<script>
	const { name, percentage, data, handleToggleModal, resetData } = $props();
</script>

<section id="hero">
	<h3 class="text-large">
		{name}, you have {data['weeks']} weeks left. make them count 🫡
	</h3>
	<div class="btns-container">
		<button onclick={handleToggleModal}>Not {name}?</button>
		<button onclick={() => {
            navigator.clipboard.writeText('https://deathandtaxes.netlify.app')
            alert('Copied ☺️')
        }} class="link-button">Copy Link</button>
		<button onclick={resetData} class="link-button">Reset Data</button>
	</div>
	<div class="progress-bar">
		<div style:width={percentage}>
			<div>
				<i class="fa-sold fa-baby"></i>
				<h6 class="bar-label">Birth</h6>
			</div>
			<h6>{percentage}</h6>
		</div>
		<div>
			<h6 class="bar-label">Death</h6>
			<i class="fa-solid fa-skull"></i>
		</div>
	</div>
</section>

<style>
</style>
